dj_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("ecommerce/", include('ecommerce.urls', namespace="ecommerce"))
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

ecommerce/urls.py
from django.urls import path

from .views import (
    ProductListView,
    CheckoutView,
    ProductDetailView,
    OrderSummaryView,
    add_to_cart,
    add_to_cart_summary,
    remove_from_cart,
    remove_from_cart_summary,
    remove_one_item,
    add_to_cart_list,
    remove_from_cart_list,
    remove_one_item_list,
    add_to_cart_summary,
    remove_one_item_summary,
    remove_from_cart_summary,
    PaymentView,
    CouponView,
    RefundView
    
)


app_name= "ecommerce"

urlpatterns = [
    path("request-refund/", RefundView.as_view(), name='request-refund'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path("checkout/", CheckoutView.as_view() , name= "checkout"),
    path("add-coupon/", CouponView.as_view(), name="add-coupon"),
    path('', ProductListView.as_view(), name= "product-list"),
    path("<slug:slug>/", ProductDetailView.as_view(), name= "product-detail"),
    
    path("add-to-cart/<slug:slug>/", add_to_cart, name = "add-to-cart"),
    path("remove-from-cart/<slug:slug>/",remove_from_cart, name= "remove-from-cart"),
    path("add-to-cart-list/<slug:slug>/", add_to_cart_list, name = "add-to-cart-list"),
    path("add-to-cart-summary/<slug:slug>/", add_to_cart_summary, name = "add-to-cart-summary"),

    path("remove-from-cart-list/<slug:slug>/",remove_from_cart_list, name= "remove-from-cart-list"),
    path("remove-from-cart-summary/<slug:slug>/",remove_from_cart_summary, name= "remove-from-cart-summary"),
    

    path("add-to-cart-list/<slug:slug>/", add_to_cart_list, name = "add-to-cart-list"),
    path("remove_one_item/<slug:slug>/", remove_one_item, name= "remove-one-item"),
    path("remove_one_item_summary/<slug:slug>/", remove_one_item_summary, name= "remove-one-item-summary"),

    
    path("remove_one_item_list/<slug:slug>/", remove_one_item_list, name= "remove-one-item-list"),
    path("order-summary", OrderSummaryView.as_view(), name = "order-summary"),
    
]

templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dj-Ecommerce</title>

    {% block extra_head %}
    {% endblock extra_head %}
    <link rel="stylesheet" href="{% static "style.css" %} ">
    {% comment %} <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet"> {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    

</head>
    
<body>
    {% include 'navbar.html' %}

    <div class="mt-5 pt-4">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info-bg alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        </div>
    
    
    {% block content %}
    
    {% endblock content %}

    {% include 'footer.html' %}

    {% include 'scripts.html' %}

    {% block extra_scripts %}   
    
    {% endblock extra_scripts %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src= " {% static 'static.js' %}"></script>

</body>
</html>

templates/cart.html
 {% if num >= 1 %}
    <a href="{{object.get_add_to_cart_url}} " class="btn btn-warning" id="cart">
        <span class="material-symbols-outlined">add</span>
    </a>
    <span>{{num}} </span>
    <a href="{{object.get_remove_one_item}} " class="btn btn-warning" id="cart">
        <span class="material-symbols-outlined">remove</span>
    </a>
{% else %}
    <a href="{{object.get_absolute_url}} " class="btn btn-warning" id="cart" onclick="getquantity()">Add to Cart</a>
    

{% endif %}

templates/checkout.html
{% extends "base.html" %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block content %}

  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>Shipping address</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                  <label for="shipping_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
                  <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>

              <h3>Billing address</h3>

              <div class='hideable_billing_form'>
                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address' class='form-control' />
                  <label for="billing_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2' class='form-control' />
                  <label for="billing_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4 {% if form.billing_country.errors %}is-invalid{% endif %}">
                    <label for="country">Country</label>
                    {{ form.billing_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="billing_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control {% if form.billing_zip.errors %}is-invalid{% endif %}' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>

                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                  <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
                </div>

              </div>

              {% if default_billing_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
                <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}
              <hr>

              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          {% include "order-snippet.html" %}
        </div>

      </div>

    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}
<script>
  var hideable_shipping_form = $('.hideable_shipping_form');
  var hideable_billing_form = $('.hideable_billing_form');


  var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
  var use_default_billing = document.querySelector("input[name=use_default_billing]");

  use_default_shipping.addEventListener('change', function() {
    if (this.checked) {
      hideable_shipping_form.hide();
    } else {
      hideable_shipping_form.show();
    }
  })

  use_default_billing.addEventListener('change', function() {
    if (this.checked) {
      hideable_billing_form.hide();
    } else {
      hideable_billing_form.show();
    }
  });

</script>
{% endblock extra_scripts %}

templates/footer.html
<hr class="my-4">
  <footer class="bg-warning">
    <!-- Social icons -->
    <div class="pb-4 bg-warning">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2022 Copyright: TopCommerce
      {% comment %} <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a> {% endcomment %}
    </div>
    <!--/.Copyright-->

  </footer>

templates/navbar.html
{% load cart %}

<nav class="navbar fixed-top navbar-expand-lg white bg-warning" id="head">
    <!--Left-->
    <div class="container">
        <a href="{% url 'ecommerce:product-list' %}" id="navbar1" class="navbar-brand"><strong>TopCommerce</strong></a>

        {% comment %} <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button> {% endcomment %}


    <!--right-->
        <div class="navbar navbar-expand" id="navbarNavAltMarkup">
            
              <ul class="navbar-nav nav-flex-icons">
                {% if request.user.is_authenticated %}
                    <li class="nav-item" >
                        <a href="{% url 'ecommerce:order-summary' %}" class="nav-link"> 
                            <div id="shop">
                                <div class="material-icons  item2 position-relative">shopping_cart 
                                </div>
                                <span class="position-absolute start-78 translate-middle badge rounded-circle bg-danger">
                                    {{request.user|cart_item_count}}
                                </span> 
                            
                                
                                <span class="item2"> Cart </span>
                            </div>
                        </a>
                    </li>
        
                    <li class="nav-item">
                        <a href="{% url "account_logout" %}" class="nav-link">
                        <span class="item2"> Logout </span></a>
                    </li>
                
                {% else %}
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                    <span class="item2" > Login </span>
                    </a> 
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                    <span class="item2"> Signup </span>
                    </a>
                </li>
                {% endif %}
              </ul>   
        </div>
        

    </div>



</nav>

templates/order-snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-orderproduct-center mb-3">
        <span class="text-muted">Your Cart</span>
        <span class="badge badge-secondary">{{order.orderproduct.count}} </span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.orderproduct.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div class="">
                <h6 class="my-0">{{order_item.quantity}} x {{order_item.item.title}} </h6>
                <small class="text-muted">{{order_item.item.description}} </small>
            </div>
            <span class="text-muted">₦{{order_item.get_final_price}} </span>
        </li>
        
        {% endfor %}

        {% if order.coupon %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{order.coupon.code}} </small>
            </div>
            <span class="text-success">-₦{{order.coupon.amount}} </span>
        </li>
    
        {% endif %}

        <li class="list-group-item d-flex justify-content-between">
            <span>Total (₦)</span>
            <strong>₦{{order.get_total}} </strong>
        </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form action="{% url "ecommerce:add-coupon"  %}" class="card p-2" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{couponform.code}}
            <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>

    </form>
    {% endif %}
</div>

templates/order-summary.html
{% extends "base.html" %}


{% block content %}
    <main>
        <div class="container">
            <div class="table-responsive text-nowrap">
                <h2>Order Summary</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope='col'>#</th>
                            <th scope='col'>Item title</th>
                            <th scope='col'>Price</th>

                            <th scope='col'>Quantity</th>
                            <th scope='col'>Total Item Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order_item in order_item %}
                        <tr>
                            <th scope='row'>{{forloop.counter}} </th>
                            <td>{{order_item.product.title}} </td>
                            {% if order_item.product.discount_price %}
                                <td>
                                    <del>₦{{order_item.product.original_price}}</del>
                                    ₦{{order_item.product.discount_price}}
                                </td>
                               
                                {% else %}
                                <td>₦{{order_item.product.original_price}} </td>
                            {% endif %}
                            <td style="display:flex;">
                                <a href="{% url 'ecommerce:remove-one-item-summary' order_item.product.slug %} " style="text-decoration:none;"><span class="material-icons">remove</span>{{order_item.quantity}} </a>
                                <a href="{% url "ecommerce:add-to-cart-summary" order_item.product.slug %} "><span class="material-icons">add</span> </a>
                            </td>
                            <td>
                            <span style="margin-right:1rem;">
                                {% if order_item.product.discount_price %}
                                    ₦{{order_item.get_discounted_product_price}}
                                    <span class="btn btn-success">Saving ₦{{order_item.get_amount_saved}}</span>
                            {% else %}
                            ₦{{order_item.get_total_product_price}}
                            {% endif %}
                            </span>
                            <a href="{% url 'ecommerce:remove-from-cart-summary' order_item.product.slug %} "><span class="material-icons" style="color: red; float: right">delete</span> </a>
                            </td>

                            
                        </tr>
                        {% empty %}
                            <tr>
                                <td colspan='5'>Your cart is empty</td>
                            </tr>
                            <tr>
                                <td colspan="5">
                                    <a href="/ecommerce" class="btn btn-primary float-right">Continue shopping</a>
                                </td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="5">
                                <a href="{% url 'ecommerce:checkout' %} " class="btn btn-warning">Proceed to checkout</a>
                                <a href="/ecommerce" class="btn btn-warning float-right">Continue shopping</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </main>




{% endblock content %}

templates/payment.html
{% extends "base.html" %}

{% block extra_head %}
<style>

#stripeBtnLabel {
  font-family: "Helvetica Neue", Helvetica, sans-serif;
  font-size: 16px;
  font-variant: normal;
  padding: 0;
  margin: 0;
  -webkit-font-smoothing: antialiased;
  font-weight: 500;
  display: block;
}

#stripeBtn {
  border: none;
  border-radius: 4px;
  outline: none;
  text-decoration: none;
  color: #fff;
  background: #32325d;
  white-space: nowrap;
  display: inline-block;
  height: 40px;
  line-height: 40px;
  box-shadow: 0 4px 6px rgba(50, 50, 93, .11), 0 1px 3px rgba(0, 0, 0, .08);
  border-radius: 4px;
  font-size: 15px;
  font-weight: 600;
  letter-spacing: 0.025em;
  text-decoration: none;
  -webkit-transition: all 150ms ease;
  transition: all 150ms ease;
  float: left;
  width: 100%
}

button:hover {
  transform: translateY(-1px);
  box-shadow: 0 7px 14px rgba(50, 50, 93, .10), 0 3px 6px rgba(0, 0, 0, .08);
  background-color: #43458b;
}

.stripe-form {
  padding: 5px 30px;
}

#card-errors {
  height: 20px;
  padding: 4px 0;
  color: #fa755a;
}

.stripe-form-row {
  width: 100%;
  float: left;
  margin-top: 5px;
  margin-bottom: 5px;
}

/**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}

.current-card-form {
  display: none;
}

</style>
{% endblock extra_head %}

{% block content %}

  <main >
    <div class="container wow fadeIn">

      <h2 class="my-5 h2 text-center">Payment</h2>

      <div class="row">

        <div class="col-md-12 mb-4">
          <div class="card">

            {% if card %}
              <div style="padding: 5px 30px;">
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="use_default_card" id="use_default_card">
                  <label class="custom-control-label" for="use_default_card">Use default card:
                    **** **** **** {{ card.last4 }} 
                  <span>Exp: {{ card.exp_month }}/{{ card.exp_year }}</span></label>
                </div>
              </div>
            {% endif %}

            <div class="current-card-form">
              <form action="." method="post" class="stripe-form">
                  {% csrf_token %}
                  <input type="hidden" name="as_default" value="true">
                  <div class="stripe-form-row">
                    <button id="stripeBtn">Submit Payment</button>
                  </div>
                  <div id="card-errors" role="alert"></div>
              </form>
            </div>
            

            <div class="new-card-form">
              <form action="." method="post" class="stripe-form" id="stripe-form">
                  {% csrf_token %}
                  <div class="stripe-form-row" id="creditCard">
                      <label for="card-element" id="stripeBtnLabel">
                          Credit or debit card
                      </label>
                      <div id="card-element" class="StripeElement StripeElement--empty"><div class="__PrivateStripeElement" style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;"><iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame5" allowpaymentrequest="true" src="https://js.stripe.com/v3/elements-inner-card-19066928f2ed1ba3ffada645e45f5b50.html#style[base][color]=%2332325d&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js&amp;controllerId=__privateStripeController1" title="Secure payment input frame" style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; height: 19.2px;"></iframe><input class="__PrivateStripeElement-input" aria-hidden="true" aria-label=" " autocomplete="false" maxlength="1" style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;"></div></div>
                  </div>
                  <div class="stripe-form-row">
                    <button id="stripeBtn">Submit Payment</button>
                  </div>
                  <div class="stripe-form-row">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" class="custom-control-input" name="save" id="save_card_info">
                      <label class="custom-control-label" for="save_card_info">Save for future purchases</label>
                    </div>
                  </div>
                  <div id="card-errors" role="alert"></div>
              </form>
            </div>

          </div>
        </div>

        {% include "order-snippet.html" %}

      </div>

    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}

<script src="https://js.stripe.com/v3/"></script>
<script nonce="">  // Create a Stripe client.
  var stripe = Stripe('{{STRIPE_PUBLIC_KEY}}');

  // Create an instance of Elements.
  var elements = stripe.elements();

  // Custom styling can be passed to options when creating an Element.
  // (Note that this demo uses a wider set of styles than the guide below.)
  var style = {
    base: {
      color: '#32325d',
      fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
      fontSmoothing: 'antialiased',
      fontSize: '16px',
      '::placeholder': {
        color: '#aab7c4'
      }
    },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a'
    }
  };

  // Create an instance of the card Element.
  var card = elements.create('card', {style: style});

  // Add an instance of the card Element into the `card-element` <div>.
  card.mount('#card-element');

  // Handle real-time validation errors from the card Element.
  card.addEventListener('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });
  // Handle form submission.
  var form = document.getElementById('stripe-form');
  form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(card).then(function(result) {
      if (result.error) {
        // Inform the user if there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server.
        
        stripeTokenHandler(result.token);
      }
    });
  });

  // Submit the form with the token ID.
  function stripeTokenHandler(token) {
    
    
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('stripe-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    
    form.appendChild(hiddenInput);
    
    // Submit the form
    form.submit();
  }

  var currentCardForm = $('.current-card-form');
  var newCardForm = $('.new-card-form');
  var use_default_card = document.querySelector("input[name=use_default_card]");
  use_default_card.addEventListener('change', function() {
    if (this.checked) {
      newCardForm.hide();
      currentCardForm.show();
    } else {
      newCardForm.hide();
      currentCardForm.hide();
    }
  })

</script>

{% endblock extra_scripts %}

templates/product-detail.html
{% extends "base.html" %}

{% block content %}
    <main class="mt-5 pt-4">
        <div class="container dark-grey-text mt-5">
            <div class="row wow fadeIn">
                <div class="col-md-6 mb-4">
                    <div class="view overlay">

                        <img src="{{ object.product_image.url }}" class="card-img-top" id="img2">
                          <div class="mask rgba-white-slight"></div>
                        </a>
                      </div>

                </div>
                <div class="col-md-6 md-4">
                    <div class="p-4">
                        <p class="lead">
                            {% if object.discount_price %}
                            <span class="mr-1">
                                <del>₦{{object.original_price}} </del>
                            </span>
                            <span class="mr-1">
                                ₦{{object.discount_price}}
                            </span>
                            {% else %}
                            <span class="mr-1">
                                ₦{{object.original_price}}
                            </span>
                            {% endif %}
                        </p>

                        <p class="lead font-weight-bold">Description</p>
                        <p>{{object.description}} </p>

                          <a href="{{object.get_add_to_cart_url}} " class="btn btn-warning btn-md my-0 p">Add to cart</a>
                          <a href="{{object.get_remove_from_cart}} " class="btn btn-danger btn-md my-0 p">
                            Remove from cart
                          </a>
              
                    </div>
                </div>
            </div>
        </div>
    </main>





{% endblock content %}

templates/request-refund.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block content %}

<main>
    <div class="container">
        <h2>Request Refund</h2>
        <form method='post'>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</main>
{% endblock content %}